targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/**/model/**
        enabled: true
        options:
          any_map: true
          field_rename: snake
      squadron_builder:worker_builder:
        generate_for:
          - lib/**
        enabled: true
        options:
          build_extensions:
            {
              "{{dir}}/{{file}}.dart":
                [
                  "{{dir}}/_gen/{{file}}.worker.g.dart",
                  "{{dir}}/_gen/{{file}}.vm.g.dart",
                  "{{dir}}/_gen/{{file}}.web.g.dart",
                  "{{dir}}/_gen/{{file}}.stub.g.dart",
                  "{{dir}}/_gen/{{file}}.activator.g.dart",
                ],
            }
          with_finalizers: false
