call dart compile js .\lib\src\pi-digits\browser\pi_digits_worker.dart -o .\web\workers\pi_digits_worker.dart.js -m
call dart compile js .\lib\src\thumbnails\browser\thumbnail_worker.dart -o .\web\workers\thumbnail_worker.dart.js -m
call dart compile js .\lib\src\text-size\browser\my_worker.dart -o .\web\workers\my_worker.dart.js -m
call dart compile js .\lib\src\parser\browser\parser_worker.dart -o .\web\workers\parser_worker.dart.js -m
call dart compile js .\lib\src\parser2\browser\parser2_worker.dart -o .\web\workers\parser2_worker.dart.js -m
call dart compile js .\lib\src\codegen\generated\codegen.web.g.dart -o .\web\workers\codegen.web.g.dart.js -m
call dart compile js .\lib\src\perf\generated\perf.web.g.dart -o .\web\workers\perf.web.g.dart.js -m
call dart compile js .\lib\src\json\generated\json_service.web.g.dart -o .\web\workers\json_service.web.g.dart.js -m
call dart compile js .\lib\src\binary-data-uri\generated\base64_uri_data_decoder.web.g.dart -o .\web\workers\base64_uri_data_decoder.web.g.dart.js -m
