targets:
  $default:
    builders:
      squadron_builder:worker_builder:
        generate_for:
          - lib/**
        enabled: true
        options:
          build_extensions:
            {
              "{{dir}}/{{file}}.dart":
                [
                  "{{dir}}/generated/{{file}}.worker.g.dart",
                  "{{dir}}/generated/{{file}}.vm.g.dart",
                  "{{dir}}/generated/{{file}}.web.g.dart",
                  "{{dir}}/generated/{{file}}.stub.g.dart",
                  "{{dir}}/generated/{{file}}.activator.g.dart",
                ],
            }
          with_finalizers: true
