@SET OPTIM=-O2
@ECHO.Compile Web workers to Web Assembly, optim = %OPTIM%...
@ECHO.
@ECHO.   pi_digits_worker.dart...
@CALL dart compile wasm .\lib\src\pi-digits\generated\pi_digits_service.web.g.dart -o .\web\workers\pi_digits_service.web.g.dart.wasm %OPTIM% & ECHO ON
@ECHO.
@ECHO.   thumbnail_worker.dart...
@CALL dart compile wasm .\lib\src\thumbnails\generated\thumbnail_service.web.g.dart -o .\web\workers\thumbnail_service.web.g.dart.wasm %OPTIM% & ECHO ON
@ECHO.
@ECHO.   text_size_worker.dart...
@CALL dart compile wasm .\lib\src\text-size\generated\text_size_service.web.g.dart -o .\web\workers\text_size_service.web.g.dart.wasm %OPTIM% & ECHO ON
@ECHO.
@ECHO.   parser_worker.dart...
@CALL dart compile wasm .\lib\src\parser\generated\parser_service.web.g.dart -o .\web\workers\parser_service.web.g.dart.wasm %OPTIM% & ECHO ON
@ECHO.
@ECHO.   parser2_worker.dart...
@CALL dart compile wasm .\lib\src\parser2\generated\parser2_service.web.g.dart -o .\web\workers\parser2_service.web.g.dart.wasm %OPTIM% & ECHO ON
@ECHO.
@ECHO.   parser3_worker.dart...
@CALL dart compile wasm .\lib\src\parser3\generated\parser3_service.web.g.dart -o .\web\workers\parser3_service.web.g.dart.wasm %OPTIM% & ECHO ON
@ECHO.
@ECHO.   codegen.web.g.dart...
@CALL dart compile wasm .\lib\src\codegen\generated\codegen.web.g.dart -o .\web\workers\codegen.web.g.dart.wasm %OPTIM% & ECHO ON
@ECHO.
@ECHO.   perf.web.g.dart...
@CALL dart compile wasm .\lib\src\perf\generated\perf.web.g.dart -o .\web\workers\perf.web.g.dart.wasm %OPTIM% & ECHO ON
@ECHO.
@ECHO.   json_service.web.g.dart...
@CALL dart compile wasm .\lib\src\json\generated\json_service.web.g.dart -o .\web\workers\json_service.web.g.dart.wasm %OPTIM% & ECHO ON
@ECHO.
@ECHO.Done
